apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "kubexa-agent.namespace" . }}
  name: {{ include "kubexa-agent.fullname" . }}-secret
  labels:
    {{- include "kubexa-agent.labels" . | nindent 4 }}
type: Opaque
data:
  # helm install --set secrets.grpcToken=mytoken
  # boş string de geçerli (optional: true ile agent çalışmaya devam eder)
  grpc-token: {{ .Values.secrets.grpcToken | default "" | b64enc | quote }}

  {{- if .Values.agent.buffer.redis.enabled }}
  redis-password: {{ .Values.secrets.redisPassword | default "" | b64enc | quote }}
  {{- end }}