{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "kubexa-agent.namespace" . }}
  name: {{ include "kubexa-agent.serviceAccountName" . }}
  labels:
    {{- include "kubexa-agent.labels" . | nindent 4 }}
{{- end }}